spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://192.168.56.10:3306/mall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  application:
    name: coupon
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #  id×ÔÔö
  global-config:
    db-config:
      id-type: auto
server:
  port: 8020

